/**
 * The generated `data/lemma/<code>.json` table: its shape, validation, and the
 * paradigm-cell vocabulary it is written in. Contract: docs/specs/service/lexicon.md.
 * Generated by `scripts/build-lemma-tables.mjs`; never written by hand.
 *
 * Split out of `lib/lexicon.ts` because this half of the module — validating
 * data someone else generated — is a different concern from tokenising and
 * ranking text, even though both live under the same spec.
 */

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === "object" && value !== null && !Array.isArray(value);

/**
 * The parts of speech `scripts/build-lemma-tables.mjs` ever emits. Kept as a
 * closed set here too — a table claiming a part of speech this module does not
 * know is exactly the kind of drift `loadLemmaTable` exists to catch before a
 * caller sees it.
 */
const PARTS_OF_SPEECH = [
  "verb",
  "noun",
  "propn",
  "adj",
  "adv",
  "det",
  "pron",
  "adp",
  "conj",
  "num",
  "intj",
  "part",
  "other",
] as const;
export type PartOfSpeech = (typeof PARTS_OF_SPEECH)[number];

/**
 * One vocabulary for every paradigm cell, shared across languages and across
 * source formats — see docs/specs/service/lexicon.md, "Knowing a lemma is not
 * knowing its forms". A raw source-format tag (`V;IND;PRS;3;SG`) does not match
 * this and is rejected at load time rather than passed through.
 */
const CELL_PATTERN =
  /^(?:inf|ger|part\.pres|part\.past(?:\.[mf]\.(?:sg|pl))?|(?:ind|sub)\.(?:pres|impf|pret|fut)\.[123](?:sg|pl)|cond\.[123](?:sg|pl)|imp\.[123](?:sg|pl)|(?:comp\.|sup\.)?(?:[mf]\.)?(?:sg|pl))$/;

export type Analysis = { lemma: string; pos: PartOfSpeech; cell: string | null };
export type LemmaDescription = { conjugation: string } | { gender: string };

export type LemmaTable = {
  language: string;
  seedCoverage: number;
  verbParadigmsComplete: number;
  sources: readonly { source: string; licence: string; url: string }[];
  /** `form → analyses`, likeliest first. Never the fused decomposition — see `fused`. */
  forms: Record<string, readonly Analysis[]>;
  /** `form → parts`. Simultaneous, not alternative — kept apart from `forms` on purpose. */
  fused: Record<string, readonly string[]>;
  /** What a lemma *is*, apart from any of its forms: a verb's class, a noun's gender. */
  lemmas: Record<string, Record<string, string>>;
};

export type Resolution =
  | { kind: "unknown"; form: string }
  | { kind: "single"; form: string; analysis: Analysis }
  | { kind: "ambiguous"; form: string; analyses: readonly Analysis[] }
  | { kind: "fused"; form: string; parts: readonly string[] };

const validateSources = (input: unknown, errors: string[]) => {
  if (!Array.isArray(input) || input.length === 0) {
    errors.push("sources: required, non-empty array");
    return [];
  }
  for (const [i, entry] of input.entries()) {
    if (
      !isRecord(entry) ||
      typeof entry.source !== "string" ||
      typeof entry.licence !== "string" ||
      typeof entry.url !== "string" ||
      entry.source === "" ||
      entry.licence === "" ||
      entry.url === ""
    ) {
      errors.push(`sources[${i}]: requires source, licence and url`);
    }
  }
  return input as { source: string; licence: string; url: string }[];
};

/** One analysis is exactly `[lemma, pos, cell]`, `pos` known, `cell` documented or empty. */
const validateAnalysis = (item: unknown, path: string, errors: string[]): Analysis | undefined => {
  if (!Array.isArray(item) || item.length !== 3) {
    errors.push(`${path}: an analysis is exactly [lemma, pos, cell]`);
    return undefined;
  }
  const [lemma, pos, cell] = item as unknown[];
  if (typeof lemma !== "string" || lemma === "") {
    errors.push(`${path}: lemma must be a non-empty string`);
    return undefined;
  }
  if (typeof pos !== "string" || !(PARTS_OF_SPEECH as readonly string[]).includes(pos)) {
    errors.push(`${path}: "${String(pos)}" is not a known part of speech`);
    return undefined;
  }
  if (typeof cell !== "string" || (cell !== "" && !CELL_PATTERN.test(cell))) {
    errors.push(`${path}: "${String(cell)}" is not a documented paradigm cell`);
    return undefined;
  }
  return { lemma, pos: pos as PartOfSpeech, cell: cell === "" ? null : cell };
};

const validateForms = (input: unknown, errors: string[]): Record<string, Analysis[]> => {
  const forms: Record<string, Analysis[]> = {};
  if (!isRecord(input)) {
    errors.push("forms: required object");
    return forms;
  }
  for (const [form, raw] of Object.entries(input)) {
    if (!Array.isArray(raw) || raw.length === 0) {
      errors.push(`forms.${form}: must be a non-empty array of analyses`);
      continue;
    }
    const analyses = raw
      .map((item, i) => validateAnalysis(item, `forms.${form}[${i}]`, errors))
      .filter((a): a is Analysis => a !== undefined);
    if (analyses.length > 0) forms[form] = analyses;
  }
  return forms;
};

const validateFused = (input: unknown, errors: string[]): Record<string, string[]> => {
  const fused: Record<string, string[]> = {};
  if (!isRecord(input)) {
    errors.push("fused: required object");
    return fused;
  }
  for (const [form, raw] of Object.entries(input)) {
    if (!Array.isArray(raw) || raw.length < 2 || raw.some((p) => typeof p !== "string" || p === "")) {
      errors.push(`fused.${form}: must be an array of at least two non-empty parts`);
      continue;
    }
    fused[form] = raw as string[];
  }
  return fused;
};

const validateLemmas = (input: unknown, errors: string[]): Record<string, Record<string, string>> => {
  const lemmas: Record<string, Record<string, string>> = {};
  if (!isRecord(input)) {
    errors.push("lemmas: required object");
    return lemmas;
  }
  for (const [lemma, raw] of Object.entries(input)) {
    if (!isRecord(raw)) {
      errors.push(`lemmas.${lemma}: must be an object`);
      continue;
    }
    lemmas[lemma] = raw as Record<string, string>;
  }
  return lemmas;
};

/**
 * Validates a build-time-generated table before anything reads it. Rejects
 * rather than repairs: a table with one malformed entry is not "mostly right",
 * it is a table that was generated wrong, and the fix belongs in
 * `scripts/build-lemma-tables.mjs`, not here.
 */
export const loadLemmaTable = (
  input: unknown,
  language: string,
): { table?: LemmaTable; errors: string[] } => {
  const errors: string[] = [];
  if (!isRecord(input)) return { errors: ["lemma table must be an object"] };

  // AC-20 · a table for the wrong language resolves plausibly and is wrong
  // everywhere, which is worse than refusing to load.
  if (input.language !== language) {
    errors.push(`language: table is for "${String(input.language)}", expected "${language}"`);
  }
  if (typeof input.seedCoverage !== "number" || typeof input.verbParadigmsComplete !== "number") {
    errors.push("seedCoverage and verbParadigmsComplete: required numbers");
  }

  const sources = validateSources(input.sources, errors);
  const forms = validateForms(input.forms, errors);
  const fused = validateFused(input.fused, errors);
  const lemmas = validateLemmas(input.lemmas, errors);

  if (errors.length) return { errors };
  return {
    errors: [],
    table: {
      language: input.language as string,
      seedCoverage: input.seedCoverage as number,
      verbParadigmsComplete: input.verbParadigmsComplete as number,
      sources,
      forms,
      fused,
      lemmas,
    },
  };
};
