import { describe, expect, it } from "vitest";

import {
  ES_IDENTICAL_COGNATES,
  MAX_GLOSS_CHARS,
  SHIPPED_ES_POOL_SIZE,
  loadSpanishMeaningRecallDeck,
  validateStarterDeck,
} from "@/lib/starter-deck";

/**
 * These assert the shipped data, not just the loader. The pool is generated by
 * `scripts/build-starter-deck.mjs` from sources that change under us — a
 * frequency list, a lemma table, a third-party dictionary — so the properties
 * the rest of the app relies on have to be checked against the committed file
 * rather than trusted to the generator that produced it.
 */
describe("starter-deck", () => {
  const result = loadSpanishMeaningRecallDeck();
  const cards = result.status === "ok" ? result.deck.cards : [];

  it("loads the shipped Spanish meaning-recall pool", () => {
    expect(result.status).toBe("ok");
    if (result.status !== "ok") return;
    expect(result.deck.language).toBe("es");
    expect(result.deck.taskType).toBe("meaning-recall");
    expect(result.deck.cards.length).toBe(SHIPPED_ES_POOL_SIZE);
    expect(result.deck.cards[0]?.taskId).toBe("es:el:meaning-recall");
    expect(result.deck.cards[0]?.frequencyRank).toBe(1);
  });

  it("ranks every card uniquely and consecutively", () => {
    expect(cards.map((card) => card.frequencyRank)).toEqual(
      cards.map((_, index) => index + 1),
    );
    expect(new Set(cards.map((card) => card.taskId)).size).toBe(cards.length);
    expect(new Set(cards.map((card) => card.lemma)).size).toBe(cards.length);
  });

  it("gives every card a usable gloss", () => {
    const empty = cards.filter(
      (card) => card.back.trim() === "" || card.front.trim() === "" || card.lemma.trim() === "",
    );
    expect(empty).toEqual([]);

    const overlong = cards.filter((card) => card.back.length > MAX_GLOSS_CHARS);
    expect(overlong.map((card) => card.lemma)).toEqual([]);
  });

  it("never shows a card whose back merely repeats its front", () => {
    // A gloss equal to the lemma is the signature of a failed dictionary
    // lookup. The exceptions are real cognates and are listed as data, so a
    // new one has to be added deliberately rather than absorbed silently.
    const repeated = cards.filter((card) => card.back === card.lemma).map((card) => card.lemma);
    expect(repeated.sort()).toEqual([...ES_IDENTICAL_COGNATES].sort());
  });

  it("keeps the task and word ids derivable from the lemma", () => {
    const wrong = cards.filter(
      (card) => card.taskId !== `es:${card.lemma}:meaning-recall` || card.wordId !== `es:${card.lemma}`,
    );
    expect(wrong.map((card) => card.lemma)).toEqual([]);
  });

  it("rejects an invalid deck", () => {
    const invalid = validateStarterDeck({ language: "es", taskType: "x", cards: [] });
    expect(invalid.status).toBe("error");
    if (invalid.status === "error") {
      expect(invalid.errors.join(" ")).toMatch(/cards/);
    }
  });
});
